FROM gradle:8.0.2-jdk17 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN ./gradlew :api:bootJar

FROM openjdk:17-jdk-slim
COPY --from=build /home/gradle/src/build/libs/Gatos*-all.jar gatos.jar
CMD ["java", "-jar", "gatos.jar"]
