server:
  error:
    include-message: always

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

auth0:
  audience: https://gatos-backend.mondaylunch.club
  management:
    token_request_url: https://mondaylunchdev.eu.auth0.com/oauth/token
    client_id: ${AUTH0_CLIENT_ID}
    client_secret: ${AUTH0_CLIENT_SECRET}
    audience: https://mondaylunchdev.eu.auth0.com/api/v2/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://mondaylunchdev.eu.auth0.com/
