server:
  error:
    include-message: always

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

auth0:
  audience: ${AUTH0_AUDIENCE}
  management:
    token_request_url: ${AUTH0_TOKEN_URL}
    client_id: ${AUTH0_CLIENT_ID}
    client_secret: ${AUTH0_CLIENT_SECRET}
    audience: ${AUTH0_MANAGEMENT_AUDIENCE}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER}
