name: Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"
      - name: Run services in background
        run: |
          docker-compose up -d
      - name: Run tests
        env:
          BACKEND_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          BACKEND_AUTH0_CLIENT_SECRET: ${{ secrets.BACKEND_AUTH0_CLIENT_SECRET }}
          AUTH0_ISSUER: ${{ vars.AUTH0_ISSUER }}
          AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
          AUTH0_TOKEN_URL: ${{ vars.AUTH0_TOKEN_URL }}
          AUTH0_MANAGEMENT_AUDIENCE: ${{ vars.AUTH0_MANAGEMENT_AUDIENCE }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: ./gradlew test --stacktrace --parallel
