name: Test
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: 17
                  cache: "gradle"
            # a .env file is also a valid properties file
            - name: Make envfilection@master"
              uses: SpicyPizza/create-envfile@v1.3
              with:
                envkey_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
                envkey_AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
                envkey_AUTH0_ISSUER: ${{ vars.AUTH0_ISSUER }}
                envkey_AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
                envkey_AUTH0_TOKEN_URL: ${{ vars.AUTH0_TOKEN_URL }}
                envkey_AUTH0_MANAGEMENT_AUDIENCE: ${{ vars.AUTH0_MANAGEMENT_AUDIENCE }}
                file_name: secrets.properties
            - name: Run services in background
              run: |
                  docker-compose up -d
            - name: Run tests
              run: ./gradlew test --stacktrace --parallel
